cache:           # Cache persists between pipelines
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .next/

image: node:latest

stages:          # List of stages for jobs, and their order of execution
  - build
  - test

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - npm install
    - npm run build
    - chmod u+x node_modules

unit-test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  script:
    - echo "Running unit tests..."

